In [250]:
import cv2
import numpy as np
import math

In [254]:
#Получить изображение из файла
img = cv2.imread('Final_for_bag.png',0)
#Фильтрация изображения
img = cv2.medianBlur(img,5)
img = cv2.medianBlur(img,5)
img = cv2.GaussianBlur(img,(11,11),10)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)


cv2.imwrite('5.png',img)
cv2.imwrite('10.png',img2)

True

In [255]:
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,2,0.001,param1=40,param2=170,minRadius=1,maxRadius=500)



In [256]:
b = 0
circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # нарисовать окружности
    cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # нарисовать центры окружностей
    cv2.circle(cimg,(i[0],i[1]),2,(0,255,0),3)
    b +=1

cv2.imwrite('Circles.png',cimg)
print(circles)

[[[647 381 182]
  [645 365 186]
  [643 383 186]
  [645 371 180]
  [643 363 183]
  [643 375 178]
  [631 389 194]
  [621 381 190]
  [653 385 193]
  [627 385 180]
  [659 387 171]]]


In [237]:
circles.shape

(1, 11, 3)

In [247]:
circles = circles.reshape(circles[0].shape) 
circles_mean = np.mean(circles, axis = 0)
circles_mean  = np.uint16(np.around(circles_mean))
cv2.circle(cimg,(circles_mean[0],circles_mean[1]),i[2],(0,0,255),3)
cv2.circle(cimg,(circles_mean[0],circles_mean[1]),2,(0,0,255),2)
cv2.imwrite('Circles.png',cimg)
print(i[2])

183


In [229]:
cv2.circle(cimg,(i[0],i[1]),2,(0,255,0),3)
    b +=1

cv2.imwrite('Circles.png',cimg)
print(circles)

array([644, 367, 182], dtype=uint16)

In [262]:
def scalarh(x1,y1,x2,y2,x3,y3):
    x2 = math.fabs(x1-x2)
    
    x3 = math.fabs(x1-x3)
    y2 = math.fabs(y1-y2)
    y3 = math.fabs(y1-y3)
    
    s = (x2*x3+y2*y3)
    print('s = ', s)
    f = (math.sqrt(x2**2+y2**2)* math.sqrt(x3**2+y3**2))
    print('f = ', f)
    s = s/f
    
    return math.acos(s) 

r = 30 cm 

In [263]:
scalarh(0,0,4,0,0,3)

s =  0.0
f =  12.0


1.5707963267948966

In [56]:
circles = circles.reshape(12,3) 
circles_mean = np.mean(circles, axis = 0)

In [89]:
#Получить изображение из файла
img = cv2.imread('2.jpg',0)
#Фильтрация изображения
img = cv2.medianBlur(img,5)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)


circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,0.1,param1=80,param2=90,minRadius=10,maxRadius=200)

circles = np.uint16(np.around(circles))


In [96]:
bag = np.uint16(np.around(bag))
bag1 = cv2.imread('nn.jpg',0)
#Фильтрация изображения

bag1 = cv2.cvtColor(bag1,cv2.COLOR_GRAY2BGR)

In [97]:
circles = circles.reshape(12,3) 
circles_mean = np.mean(circles, axis = 0)
circles_mean  = np.uint16(np.around(circles_mean))

cv2.circle(bag1,(circles_mean[0],circles_mean[1]),8,(0,0,255),3)
cv2.imwrite('Circles.png',bag1)

True

In [69]:
circles[0].shape

(12, 3)

In [85]:
bag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint16)