In [28]:
import cv2
import numpy as np
cap = cv2.VideoCapture("result_720.mp4")
fps = cap.get(cv2.CAP_PROP_FPS)
print(fps)
import matplotlib.pylab as plt
def superimposition_mask(x,y):
    new = np.zeros(y.shape)
    for i in range(y.shape[2]):
        new[:,:,i] = x*y[:,:,i]
    return new
def mask(a, x1, x2, y1, y2, z1, z2):
    h_min = np.array((x1, y1, z1), np.uint8)
    h_max = np.array((x2, y2, z2), np.uint8)
    return cv2.inRange(a, h_min, h_max)

24.98819720779659


In [33]:
import cv2
import numpy as np


if __name__ == '__main__':
    def nothing(*arg):
        pass

#cv2.namedWindow( "result" ) # создаем главное окно


cap = cv2.VideoCapture("result_720.mp4")


crange = [0,0,0, 0,0,0]
#i = 0
while True:
    ch = cv2.waitKey(45)
    if ch == 23:
        break
    #if i != 10:
        #i = 0
        #continue
   # else:
        #i += 1
    flag, img = cap.read()
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )
 

    # накладываем фильтр на кадр в модели HSV
    thresh = mask(hsv, 0,238,166,255,157,255)
   
    new = superimposition_mask(thresh, img)
    print( img)
    new = new.astype(np.uint8)
    new = cv2.medianBlur(new,5)
    new = cv2.cvtColor(new, cv2.COLOR_BGR2GRAY)
    #hsv = cv2.cvtColor(new, cv2.COLOR_HSV2BGR )
    #hsv = cv2.cvtColor(hsv, cv2.COLOR_BGR2GRAY)
    circles = cv2.HoughCircles(new, cv2.HOUGH_GRADIENT,1,0.1,param1=70,param2=80,minRadius=10,maxRadius=200)
    print(circles)
    if None not in  circles:
        circles = np.uint16(np.around(circles))
        for i in circles[0,:]:
    # нарисовать центры окружностей
            cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
            cv2.circle(new,(i[0],i[1]),2,(0,0,255),3)
    #cv2.imshow('result', new) 
        cv2.imwrite("new.jpg",new)
    ch = cv2.waitKey(33)
    if ch == 27:
        break

cap.release()
#cv2.destroyAllWindows()

[[[230 208 196]
  [230 208 196]
  [230 208 196]
  ...
  [ 19 125   0]
  [ 19 125   0]
  [ 19 125   0]]

 [[230 208 196]
  [230 208 196]
  [230 208 196]
  ...
  [ 19 125   0]
  [ 19 125   0]
  [ 19 125   0]]

 [[230 208 196]
  [230 208 196]
  [230 208 196]
  ...
  [ 19 125   0]
  [ 19 125   0]
  [ 19 125   0]]

 ...

 [[236 214 202]
  [236 214 202]
  [236 214 202]
  ...
  [ 24 131   0]
  [ 23 130   0]
  [ 23 130   0]]

 [[236 214 202]
  [236 214 202]
  [236 214 202]
  ...
  [ 23 130   0]
  [ 23 130   0]
  [ 23 130   0]]

 [[236 214 202]
  [236 214 202]
  [236 214 202]
  ...
  [ 23 130   0]
  [ 23 130   0]
  [ 23 130   0]]]
None


TypeError: argument of type 'NoneType' is not iterable

In [ ]:
cap = cv2.VideoCapture("result_720.mp4")
flag, img = cap.read()
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )
 
h_min = np.array((110, 50, 50), np.uint8)
h_max = np.array((130, 255, 255), np.uint8)

    # накладываем фильтр на кадр в модели HSV
thresh = cv2.inRange(hsv, h_min, h_max)


nohsv = cv2.cvtColor(thresh, cv2.COLOR_HSV2BGR )
nohsv = cv2.cvtColor(nohsv, cv2.COLOR_BGR2GRAY)
circles = cv2.HoughCircles(nohsv,cv2.HOUGH_GRADIENT,1,20,param1=50,param2=30,minRadius=2,maxRadius=100)

circles = np.uint16(np.around(circles))

for i in circles[0,:]:
    # нарисовать центры окружностей
    cv2.circle(thresh,(i[0],i[1]),2,(0,0,255),3)
cv2.imshow('result', nohsv) 

cap.release()
cv2.imwrite('output.png',nohsv)
cv2.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture("result_720.mp4")
flag, img = cap.read()
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )
 
h_min = np.array((100, 50, 50), np.uint8)
h_max = np.array((140, 255, 255), np.uint8)

    # накладываем фильтр на кадр в модели HSV
thresh = cv2.inRange(hsv, h_min, h_max) /255
def mask(x,y):
    new = np.zeros(y.shape)
    for i in range(y.shape[2]):
        new[:,:,i] = x*y[:,:,i]
    return new
plt.imshow(mask(thresh, img))

    
        
   


In [ ]:
new = mask(thresh, img)
print(new.shape)
cv2.imwrite("new.jpg",new)

In [ ]:
z