In [4]:
import cv2
import numpy as np


In [11]:
#Получить изображение из файла
img = cv2.imread('2.jpg',0)
#Фильтрация изображения
img = cv2.medianBlur(img,5)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)



In [16]:
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,0.1,param1=80,param2=90,minRadius=10,maxRadius=200)

circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # нарисовать окружности
    cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # нарисовать центры окружностей
    cv2.circle(cimg,(i[0],i[1]),2,(0,0,255),3)
i = 1
cv2.imwrite(str(i)+'Circles.png',cimg)
print(circles)

[[[196 212 124]
  [198 214 125]
  [194 216 122]
  [200 216 126]
  [200 222 131]
  [200 220 130]
  [194 214 126]
  [196 220  73]
  [188 222 135]
  [190 214 129]
  [198 218  70]
  [192 216  75]]]


In [ ]:
cv2.imshow('Circles',cimg)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
cimg

In [19]:
type(None)

NoneType