In [1]:
import cv2
import numpy as np


In [17]:
#Получить изображение из файла
img = cv2.imread('2.jpg',0)
#Фильтрация изображения
img = cv2.medianBlur(img,5)
cimg = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)



In [18]:
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT,1,0.1,param1=70,param2=80,minRadius=10,maxRadius=200)

circles = np.uint16(np.around(circles))
for i in circles[0,:]:
    # нарисовать окружности
    cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # нарисовать центры окружностей
    cv2.circle(cimg,(i[0],i[1]),2,(0,0,255),3)
cv2.imwrite('Circles.png',cimg)
print(circles)

[[[196 212 124]
  [198 214 125]
  [194 216 122]
  [192 212 127]
  [200 216 127]
  [200 222 132]
  [194 214 126]
  [200 214 128]
  [190 224 125]
  [202 216 128]
  [200 216 128]
  [196 220  73]
  [188 214 130]
  [188 222 135]
  [190 212 128]
  [190 216 130]
  [190 214 129]
  [198 218  70]
  [192 216  75]
  [194 220  25]]]


In [ ]:
cv2.imshow('Circles',cimg)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
cimg

In [19]:
type(None)

NoneType