for video

In [1]:
import cv2
import numpy as np
cap = cv2.VideoCapture("result_720.mp4")
fps = cap.get(cv2.CAP_PROP_FPS)
print(fps)
import matplotlib.pylab as plt
def superimposition_mask(x,y):
    new = np.zeros(y.shape)
    for i in range(y.shape[2]):
        new[:,:,i] = x*y[:,:,i]
    return new
def mask(a, x1, x2, y1, y2, z1, z2):
    h_min = np.array((x1, y1, z1), np.uint8)
    h_max = np.array((x2, y2, z2), np.uint8)
    return cv2.inRange(a, h_min, h_max)

24.98819720779659


In [4]:
import cv2
import numpy as np


if __name__ == '__main__':
    def nothing(*arg):
        pass

#cv2.namedWindow( "result" ) # создаем главное окно



img = cv2.imread('3.png')


crange = [0,0,0, 0,0,0]
#i = 0
while True:


    #if i != 10:
        #i = 0
        #continue
   # else:
        #i += 1
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )
 

    # накладываем фильтр на кадр в модели HSV
    thresh = mask(hsv, 0,238,166,255,157,255)
   
    new = superimposition_mask(thresh, img)
    print( img)
    new = new.astype(np.uint8)
    new = cv2.medianBlur(new,5)
    new = cv2.cvtColor(new, cv2.COLOR_BGR2GRAY)
    #hsv = cv2.cvtColor(new, cv2.COLOR_HSV2BGR )
    #hsv = cv2.cvtColor(hsv, cv2.COLOR_BGR2GRAY)
    circles = cv2.HoughCircles(new, cv2.HOUGH_GRADIENT,1,0.1,param1=70,param2=80,minRadius=10,maxRadius=200)
    print(circles)
    if None not in  circles:
        circles = np.uint16(np.around(circles))
        for i in circles[0,:]:
    # нарисовать центры окружностей
            cv2.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
            cv2.circle(new,(i[0],i[1]),2,(0,0,255),3)
    #cv2.imshow('result', new) 
        cv2.imwrite("new.jpg",new)
    ch = cv2.waitKey(33)
    if ch == 27:
        break

cap.release()
#cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
None


TypeError: argument of type 'NoneType' is not iterable